[package]
name = "hexview"
version = "0.1.0"
authors = ["Mark Nokalt <marknokalt@live.com>"]
edition = "2018"
publish = false

[dependencies]
iced = { git = "https://github.com/hecrj/iced" , rev = "73811c3" }
iced_widgets = { path = "../../" }